version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1-stretch
    steps:
      - checkout
      - run:
          name: Echo out something!
          command: echo "hello navin from a docker image!"
      - run:
          name: Check contents of directory
          command: ls -la
      - run:
          name: Install NPM
          command: cd server && npm install
      - run:
          name: test application
          command: cd server && npm test
