jobs:
  build-test-navinism:
    docker:
      - image: circleci/node:12.13.1-stretch
    steps:
      - checkout
      - run:
          name: Echo out something!
          command: echo "hello navin from a docker image!"
      - run:
          name: Check contents of directory
          command: ls -la
      - run:
          name: Install NPM
          command: cd server && npm install
      - run:
          name: run server
          command: cd server && npm start
          background: true
      - run:
          name: test application
          command: cd server && npm test
  deploy-prod:
    docker:
      - image: circleci/node:12.13.1-stretch
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project_navinism.sh"
orbs:
  node: circleci/node@4.0.0
version: 2.1
workflows:
  build_test_deployToProd:
    jobs:
      - build-test-navinism
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build-test-navinism
