version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1-stretch
    steps:
      - checkout
      - run:
          name: Echo out something!
          command: echo "hello navin from a docker image!"
      - run:
          name: Change dir to server
          command: cd server
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: test application
          command: npm test
